### ISSUE TITLE
Ошибка получения Control в ComponentControlWrapper: Не указан defaultComponentId в конфигурационном файле

### ISSUE THREAD

**Issue by Player701** [Zidium/ServerMonitor#1]
Во время работы Zidium Server Monitor создаёт папку Logs с файлами вида ZidiumServerMonitor.exe_ZidiumInternal_ГГГГ.ММ.ДД.txt. В файлах повторяется одно и то же сообщение:
```
Error   Ошибка получения Control в ComponentControlWrapper
System.Exception: Не указан defaultComponentId в конфигурационном файле
   в Zidium.Api.ComponentControlWrapper.GetDefaultControlOnline()
   в Zidium.Api.ControlActivator`1.GetControl()
```
Я так понимаю, это связано с тем, что не указан ID компонента для мониторинга самого приложения. Однако его отсутствие не должно приводить к появлению таких сообщений.

**Comment by Zidium** [comment]
Исправлено в версии 1.3
